// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetParsedKeys(arg1:string):Promise<main.RDBAnalysis>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile():Promise<Array<string>>;

export function ParseRDB(arg1:Array<string>):Promise<string>;
